vars/Debian.yml

Installing <code>openssh-sftp-server</code> on Debian Wheezy removes <code>openssh-server</code> so it's impossible to connect again via SSH:
richard@server:~$ sudo apt-get install openssh-sftp-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
openssh-server
The following NEW packages will be installed:
openssh-sftp-server
0 upgraded, 1 newly installed, 1 to remove and 94 not upgraded.
Need to get 0 B/34.4 kB of archives.
After this operation, 605 kB disk space will be freed.
Do you want to continue [Y/n]?

Don't install openssh-sftp-server on Debian

---

meta/main.yml

I'd like to remove the apt role dependency as ansible-playbook doesn't evaluate the when statement in meta/main.yml when checking for installed role dependancies, so the apt role must be installed even when not managing any apt systems. It doesn't appear this sshd roles requires any functionality in the apt role explicitly.

Remove apt role dependancy

---

README.md
defaults/main.yml
tasks/main.yml

Allow skipping service management entirely and ensure privilege separation directory exists.
This makes it more container friendly as service management isn't necessarily used there (especially in docker) and privilege separation directory is usually created by the service scripts on start.

Make the role more container friendly

---

README.md
meta/main.yml
vars/Fedora.yml
vars/Fedora_22.yml

Based on RedHat 7 with few modifications (ed25519 hostkey for F22,
GSSAPICleanupCredentials defaults to no, s/LC_TYPE/LC_CTYPE/ in
AcceptEnv).
Tested on Fedora 20 & 22.

Add Fedora support

---

handlers/main.yml
tasks/main.yml

This uses the validate option to check the config file early, which
avoids putting bad settings in place at all, and also enables a
fail-fast behaviour (errors out when processing the template module).

Verify SSHd config early

---

tasks/main.yml

This change fixes the ansible deprecation warning for bare word "sshd_packages" (issue #38).
(I tripped over it independently, but then found the issue already logged :)

fix deprecation warning for sshd_packages (fixes issue #38)

---

meta/main.yml

This role is 16.04 compatible but isn't showing up as such on Galaxy.
Have updated `meta/main.yml` so this is no longer the case.

show xenial support on galaxy

---

README.md
meta/main.yml
vars/OpenBSD.yml

This was tested on OpenBSD 6.0 and `-current` with Ansible 2.1.2.0 and 2.2.0.0-rc1.

Support for OpenBSD

---

tasks/main.yml

Atomic Host uses unsupported package manager `rpm-ostree`. So, `ansible_pkg_mgr` is `unknown` and this task will fail. `sshd` is already in base system images. Apart from this, sshd configuration is standard for Fedora/CentOS.
I'm not sure it's the right solution. May be it's better to create new boolean variable like `sshd_manage_install` and use it here in `when`.

Don't fail without package manager

---

defaults/main.yml
vars/Archlinux.yml

This is mostly a cosmetic change. It modifies the role to match the current OpenSSH version on Archlinux (7.4p1-2 as of this writing):
- automatically disable management of /var/run/sshd (not used on Archlinux)
- remove variables set in vars/Archlinux.yml that are not currently set in the distributed config
- remove sshd_service set in vars/Archlinux.yml because it is identical to defaults/main.yml

clean Archlinux support to match the current package (openssh-7.4p1-2)

---

tasks/main.yml

I changed the state of the sshd service so if I rerun the playbook again and again, it will still work; otherwise, it will be broken at that step.

Fix sshd service state

---

templates/sshd_config.j2

This fixes the sshd_match blocks to use the contents of the matching block rather than re-using the original sshd_match block repeatedly.

Fixed sshd_match blocks

---

.gitignore
Vagrantfile
vars/RedHat_7.yml

#52 showed an issues with UsePAM on RHEL 7. Config check doesn't pick this up as status 0 is still returned. Add a note to the defaults file.

Add note about UsePAM on RHEL 7

---

handlers/main.yml

Using the `listen:` option in handlers has the benefits of producing more user friendly output (task names) and allowing multiple handlers listen to the same event.

Makes handler use listen:

---

tasks/main.yml

I think it is not the best practice to include tags in the role tasks. This could conflict with user tags. Also, there is no benefit in tagging every task in the role as this could be easily achieved by the user of the role simply by adding a tag in their playbook. This PR does simply that.
Moreover, if you still believe that there is ground for including the tag in the role, it would be much cleaner to have an import_tasks/include_tasks statement in tasks/main.yml where the task could be applied and then have the rest of the tasks in the included file without any tags.

Removes tags

---

vars/Arch Linux.yml

Hi,
My `ansible_os_family` var had the value `Arch Linux`. I symlinked the existing vars file accordingly.

Fix Arch Linux var file

---

meta/options_body
templates/sshd_config.j2

This option removes existing Unix-domain socket files before they are
used for forwarding targets.
Needed to support gpg-agent forwarding with systemd

Add StreamLocalBindUnlink option

---

vars/Debian_9.yml

OpenSSH developers have deprectated these options in OpenSSH 7.4 (which Debian 9 uses), this PR removes the options from the Debian9 config.
Stackexchange reference: https://unix.stackexchange.com/questions/337774/deprecated-options-when-restarting-openssh-in-stretch

Remove Deprecated options in default SSH config

---

handlers/main.yml
tasks/main.yml

It looks like that `ansible_virtualization_type` is not defined by default in Ansible 2.5.1 when no virtualization is used. This resulted in this role failing due to an undefined variable.
This PR simply adds a jinja2 filter, so that `ansible_virtualization_type` defaults to `None` if not set.

Fix for ansible_virtualization_type not being defined in Ansible > 2.5

---

vars/Amazon.yml

Otherwise `sshd_skip_defaults: true` will not skip default settings on Amazon Linux.
This seems a typo since any other Linux distro's var file uses `sshd_defaults` rather than `sshd`.
If the fix makes sense, I hope to see a patch release soon since it currently blocks me in my work 🙏

Amazon var name should be sshd_defaults

---

vars/Container Linux by CoreOS.yml

[CoreOS](https://coreos.com/why/) is a lightweight Linux operating system designed for clustered deployment of containers.
A few Ansible facts on CoreOS:
```
"ansible_distribution": "Container Linux by CoreOS"
"ansible_os_family": "Container Linux by CoreOS"
"ansible_distribution_major_version": "NA"
```
The original `sshd_config` for CoreOS:
```bash
core@ip-172-31-19-167 ~ $ sudo cat /etc/ssh/sshd_config 
Subsystem sftp internal-sftp
ClientAliveInterval 180
UseDNS no
UsePAM yes
PrintLastLog no # handled by PAM
PrintMotd no # handled by PAM
```
An official doc on how to customize SSH daemon on CoreOS:
https://coreos.com/os/docs/latest/customizing-sshd.html

Add CoreOS support

---

defaults/main.yml
tasks/main.yml

I would like to have a backup of the config files that are overwritten when the template is copied to a machine with an existing config file.  I propose to add a new variable, sshd_backup, which defaults to false.  If you set sshd_backup to true, it will activate the template module's backup option.

expose sshd_config template backup option with sshd_backup variable

---

templates/sshd.service.j2

This produced a non-fatal error when the service was started.

Fixes bad option in systemd service file

---

handlers/main.yml
tasks/install.yml

For chroot connection (e.g. when building images instead of working on
live hosts) one cannot restart services etc.
Also due to Ansible bug 21026 one must run systemctl instead of using
the service module, limiting support to EL 7 for the time being.

Make role work with chroot connections on EL 7.

---

meta/main.yml
tasks/variables.yml

I discovered that [tasks/variables.yml](https://github.com/willshersystems/ansible-sshd/blob/master/tasks/variables.yml#L3) was searching in the `files` directory rather than the `vars` directory. (!!!)
This patch ensures that variable files are read from the `vars` directory of the current role or playbook.
It also adds compatibility for odd-numbered Ubuntu major releases.

Fix variable loading.

---

vars/Fedora.yml

This option has been deprecated in OpenSSH for nearly two years, was the default for five years before that, and is not part of the current Fedora default configuration. It should not be included in sshd_config on Fedora systems.

Remove 'UsePrivilegeSeparation' from Fedora defaults

---

.travis.yml
handlers/main.yml

Fix errors (use of --sudo) and warnings (not having |bool on a when: clause)

Travis fixes

---

vars/RedHat_8.yml
vars/openSUSE Leap_15.yml

Based on SLE11/SP2 and a fresh installation of openSUSE Leap 42.3
... rebased version of PR #70, including requested comments:
Suse (and also other distributions which setup PAM by default) usually disable PasswordAuthentication and rely only on the KeyboardInteractive method since users could otherwise still login despite their account being disabled by PAM-specific means. See also https://superuser.com/q/894608 for an explanation of the difference between Password and KeyboardInteractive authentication.
Whether or not the file can be versioned is up to you: of course it can (for example roll out the new version for `ansible_lsb.major_release|int >= 15 and <42`, just have to make sure that the lsb package is installed), but since your current configuration could allow users to bypass …

Add vars for openSUSE Leap 15 and CentOS 8

---

tasks/install.yml

This change will allow the play to continue without error if unsupported hosts are in the lists of targed host.
The play will continue with the supported hosts end the play for the ones which are not supported.
We had an issue where this role is used in a workflow against newly deployed nodes and obviously windows hosts will fail on this. This change allowed the workflow to continue.

End_host for unsupported hosts

---

vars/Gentoo.yml

This PR adds support for all Gentoo systems. Also includes secure defaults for the sshd configuration for gentoo.

Add Gentoo support (with secure sshd defaults)

---

tasks/install.yml

Reverts willshersystems/ansible-sshd#121
end_host is 2.8+ - this breaks runs on <2.7. Will save for a major release bump.

Revert "End_host for unsupported hosts"

---

.github/workflows/ansible-lint.yml
tasks/install.yml

I've added github action to lint the playbook but unfortunately it doesn't support testing with ansible 2.7 for now

exit_host on ansible >= 2.8

---

.github/workflows/ansible-lint.yml
tasks/install.yml

From #124 - ansible 2.7 isn't support by the current linter. Move to Ansible 2.8 support as a minimum.

Minimum version is now Ansible 2.8

---

tasks/variables.yml

* OpenBSD no longer provides ansible fact "ansible_distribution_major_version" therefore set it to "ansible_distribution_version".
* ansible fact ansible_distribution_lts_version only makes sense on Ubuntu so set it only on Ubuntu -> otherwise "ansible_distribution_version"

OpenBSD and ansible_distribution_major_version

---

tasks/variables.yml

In order to collect variables, it's worth using
ansible_distribution_major_version as ansible_distribution_version
changes behaviour between ansible releases, ie [1]
This causes CentOS jobs fail with 2.8.13, as
ansible_distribution_version there is '7.8' [2]
This is partially reverts #115
[1] https://github.com/ansible/ansible/issues/57463
[2] https://zuul.opendev.org/t/openstack/build/e5ae88e08ac546ccb0e7ab99f8f0a051/log/zuul-info/host-info.centos-7.yaml#141

Use ansible_distribution_major_version in variables

---

.github/workflows/ansible-lint.yml

Ansible lint actions are currently broken for overrides of the Ansible version.  Disable until fixed.

Disable broken ansible-lint-actions

---

.travis.yml
templates/sshd_config.j2
tests/test_match.yml
tests/test_match_iterate.yml

One of the things that I noticed cumbersome in this role was the definition of Match blocks, which was supported in different ways, but limited to 11 blocks or so with `sshd['Match']`, `sshd_match` and `sshd_match_[1-9]`.
This implements alternative way describing match blocks as a list in `sshd['Match']` or `sshd_match`, keeping the old semantics unchanged for backward compatibility.

Implement more natural match blocks and test them

---

defaults/main.yml
tasks/install.yml
tasks/variables.yml
templates/sysconfig.j2
tests/test_sysconfig.yml
vars/Fedora_31.yml
vars/RedHat_6.yml
vars/RedHat_7.yml
vars/RedHat_8.yml

This should solve #141. Test playbook is written too, but it does not make much sense to run in on Ubuntu as it should not do anything there.
On the other hand, the file is just list of environment variables  so it should not hurt if unsupported values are written in there. I would be glad for review/comments/suggestions/testing.

Support /etc/sysconfig/sshd to override crypto policies and handle more advanced use cases

---

tests/tests_hostkeys_missing.yml

found this when running the role on rhel7/ansible 2.8/jinja 2.7
@Jakuje

use state: absent instead of state: missing

---

vars/FreeBSD.yml

The Subsystem entry was missing for FreeBSD OS, noticed this while provisioning a TrueNAS box. After the first provision ansible was unable to upload any files due to that missing setting. Tested this change by adjusting the role locally and rerunning it with a clean sshd_config on the remote side, worked fine.

[FreeBSD] Add Subsystem to _sshd_defaults

---

.github/workflows/ansible-centos6.yml
tasks/install.yml
tests/tests_config_namespace.yml
tests/tests_hostkeys_missing.yml
tests/tests_os_defaults.yml
tests/tests_set_uncommon.yml
vars/RedHat_6.yml
vars/main.yml

The RHEL6/CentOS 6 has a lot of issues, but we still need to make sure it works at least with best effort.
This PR removes one incompatibility which was introduced with the namespaces, adjusts testsuite to work there and adds Github Action for CentOS6 (with a tweak removing the `end_host` part, which is not compatible with Ansible version available there).

Add CentOS 6 to CI

---

.github/workflows/ansible-debian-bullseye.yml
README.md
meta/main.yml
vars/Debian_11.yml

This PR adds bullseye support to the role.
The workflow fails at the moment because there is no `roles-ansible/check-ansible-debian-bullseye-action` repo yet.
Debian 11 will be released at the 14. Aug. So it would be nice to have this role ready till saturday.

Add Debian 11 (bullseye) support

---

.github/workflows/ansible-lint.yml
meta/main.yml

Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197

Drop support for Ansible 2.8 by bumping the Ansible version to 2.9

---

README.md

Missing an `s` at the end, that fix a `404`.

README: fix meta/make_option_lists link

---

.github/workflows/ansible-centos6.yml
.github/workflows/ansible-centos7.yml
.github/workflows/ansible-centos8.yml
.github/workflows/ansible-debian-bullseye.yml
.github/workflows/ansible-debian-buster.yml
.github/workflows/ansible-debian-stretch.yml
.github/workflows/ansible-debian.yml
.github/workflows/ansible-fedora.yml
.github/workflows/ansible-ubuntu.yml
defaults/main.yml
meta/10_top.j2
tasks/install.yml
tests/requirements.yml
tests/tests_hostkeys_fips.yml
vars/RedHat_7.yml
vars/RedHat_8.yml
vars/main.yml

Previously, some of our users reported that this role has issues on FIPS systems, because it tries to generate Ed25519 keys, which are not allowed:
https://github.com/linux-system-roles/linux-system-roles.github.io/issues/66
There is a simple workaround to define list of hostkeys excluding this key type such as
```
sshd_HostKey:
- /etc/ssh/ssh_host_rsa_key
- /etc/ssh/ssh_host_ecdsa_key
```
but the defaults of the role should be FIPS aware.
The complicated thing is the FIPS detection. There are various things that are checked by the applications to turn on the FIPS mode, but generally, the kernel-space FIPS indication in `/proc/sys/crypto/fips_enabled` is most authoritative and universal place to check across different RHEL versions. Unfortunately, faking this does not work in Github …

Make the role FIPS-aware

---

.github/workflows/changelog_to_tag.yml

Description:
When a new changelog section is added to CHANGELOG.md and pushed,
changelog_to_tag.yml is triggered, which generates a new tag and
a new release.
Example of CHANGELOG.md changes:
```
[v9.9.9] - 2022-12-31
--------------------
- New feature A
- Bug fix B
```
Using this example, when the commit on CHANGELOG.md is pushed, a
new tag "v9.9.9" is added and Version v9.9.9 is released in github.
If tag "v9.9.9" already exists, the CHANGELOG.md push fails.
Note: This PR needs to be merged after https://github.com/willshersystems/ansible-sshd/pull/192 is merged since we don't want pushing the initial CHANGELOG.md triggers the action.

Add changelog_to_tag.yml to .github/workflows

---

templates/sshd_config.j2
templates/sshd_config_snippet.j2
templates/sysconfig.j2

https://github.com/willshersystems/ansible-sshd/issues/188
Ensure values are cast to string using `| string`
This shouldn't be necessary, but there seems no way to
guarantee using a version of Jinja which doesn't have this
problem.
In addition - it is not good practice to compare values to
`true` or `false` - instead, just ensure the value is a `bool`
type and evaluate in a boolean context.

Ensure values are cast to correct type

---

CHANGELOG.md

[v0.16.1] - 2022-07-28
--------------------
- add parameter RSAMinSize
Add support for the new RSAMinSize parameter.
- none
- Addition notes about secondary variables
- Fix various linting issues
- Revert incorrect module name
- tests: Do not be picky about spaces/tabs
When testing with cloud-init, it modifies the sshd_configuration and can
replace some tabs with whitespaces. This happens frequently around the
subsystem keyword. There are no functional changes, but the matching
did not work as expected.
Signed-off-by: Jakub Jelen <jjelen@redhat.com>
- the role still supports ansible 2.9
- Add CHANGELOG.md
- Add changelog_to_tag.yml to .github/workflows
Description:
When a new changelog section is added to CHANGELOG.md and pushed,
changelog_to_tag.yml is triggered, which generates a new …

Version v0.16.1 - CHANGELOG.md [citest skip]

---

.github/workflows/ansible-centos-check.yml
README.md
defaults/main.yml
meta/10_top.j2
tasks/install.yml
tasks/install_config.yml
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tests_include_present.yml
tests/tests_os_defaults.yml
vars/Fedora.yml
vars/RedHat_9.yml
vars/Ubuntu_22.yml
vars/main.yml

This is based off of #199.
This PR simplifies the logic behind the drop-in config files and also allows the user to use drop-in configs even if the distribution does not support it out of the box.

Makes drop-in functionality configurable by the user

---

CHANGELOG.md

[v0.17.0] - 2022-08-31
--------------------
- Make drop-in config file functionality configurable by user
This PR simplifies the logic behind the drop-in config files and also
allows the user to use drop-in configs even if the distribution does not
support it out of the box.
- Allow user to override variables
A previous commit hardcoded many variables to the values under vars/,
making it impossible for the user to parameterize things like the systemd
service name. The assumption was that the __sshd_* variables were useless
in an effort to blindly adhere to best practices, but they were crucial in
allowing flexibility to the user.
- Ensure values are cast to correct type
https://github.com/willshersystems/ansible-sshd/issues/188
This shouldn't be necessary, but there seems no way to …

Version v0.17.0 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

[v0.18.0] - 2022-09-27
--------------------
- Adding support for OpenWrt 21.03
- Add final version of RequiredRSASize
Keep the old version for backward compatibility
Upstream commit:
https://github.com/openssh/openssh-portable/commit/1875042c
- Update source template to match generated files
- Remove legacy files
- Update pre-commit plugins to latest
- Linting fixes
- keep v prefix in version/tag
Keep the `v` prefix in the version/tag

Version v0.18.0 - CHANGELOG.md [citest skip]

---

meta/main.yml
tasks/install_service.yml
tasks/main.yml

One of the issues is visible in the latest run of ansible-lint:
```
ERROR    Computed fully qualified role name of sshd does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:
galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead
```
where the ansible lint did not manage to figure out the namespace (probably). When executing the lint again, I got another warnings that I fixed too

Fix new linting issues

---

README.md
defaults/main.yml
meta/collection-requirements.yml
tasks/find_ports.yml
tasks/firewall.yml
tasks/install.yml
tasks/selinux.yml
tests/tests_firewall_selinux.yml

To simplify supporting running SSHD on different port, we would like to allow the sshd role to manage both SELinux and Firewall on RHEL-based systems (the roles we are using are supported only on these). This is done along the lines with the similar requirements implemented in other roles, for example [cockpit](https://github.com/linux-system-roles/cockpit/pull/73), [postfix](https://github.com/linux-system-roles/postfix/pull/56). It should not have any effect on other OSes.
The tests are currently not executed in the upstream CI, because they are containers without options to customize either firewall or selinux to my best understanding so the test will have to run only downstream with real VMs (unless there is some trick). The provided test is also quite basic, but it can be improved …

Add support for managing selinux and firewall on RHEL

---

.github/workflows/woke.yml
CHANGELOG.md
tests/tests_include_present.yml

Add check for non-inclusive language
Add a check for usage of terms and language that is considered non-inclusive. We are using the woke tool for this with a wordlist that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Clean up / Workaround non-inclusive words
- CHANGELOG.md
- tests/tests_include_present.yml

Add check for non-inclusive language; Clean up / Workaround non-inclusive words

---

vars/Fedora_36.yml
vars/Fedora_37.yml

The Fedora commit introducing this change (now in Rawhide/Fedora 38 only):
https://src.fedoraproject.org/rpms/openssh/c/7a21555354a2c5e724aa4c287b640c24bf108780
Fedora 38 is to be released on 04 Apr 2023 (if all goes well) so there is no need to hurry with the applying of the change and releasing it, but it would be good to be ready.
Anything older than Fedora 36 is EOL [1] so I do not think it is worth keeping some compatibility with these versions, but if you disagree, I can provide more symlinks. We can probably remove the Fedora 31 configuration file too, but it would be a separate change.
[1] https://docs.fedoraproject.org/en-US/releases/eol/

Fedora 38 has no longer non-standard hostkey permissions

---

meta/01_ansible_head.j2
templates/sshd_config.j2
templates/sysconfig.j2

Add repo and role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by ansible-sshd role. It may also be used for future analysis.

Fingerprint ansible-sshd managed config files

---

meta/10_top.j2
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tests_indent.yml

Inspired by similar issue reported and fixed in ssh client role https://github.com/linux-system-roles/ssh/pull/80/
This wont work in RHEL6 (not allowed AcceptEnv in match blocks) so just skip it here.

Make sure the list options are correctly indented

---

.github/workflows/ansible-debian-check.yml

This version is EOL since last year and various failures happen.
Fixes: #228

ci: Drop testing on Debian stretch (9)

---

.github/workflows/commitlint.yml
commitlint.config.js

linux-system-roles move to using the conventional commits format to automate collecting changelog and release notes, and automate identifying version of releases.
For more information, see
- General conventional commits specs in https://www.conventionalcommits.org/en/v1.0.0/,
- Conventional Commits format in system roles' Contribute https://linux-system-roles.github.io/contribute.html#conventional-commits-format

ci: Add commitlint GitHub action to ensure conventional commits

---

.github/workflows/ansible-centos-check.yml
tests/tests_firewall_selinux.yml

Do not test with selinux or firewall if the platform does not support
those roles.

test: skip selinux or firewall role test where not supported

---

.github/workflows/ansible-debian-check.yml
README.md
meta/main.yml
tests/tasks/setup.yml
vars/Debian_10.yml
vars/Debian_11.yml
vars/Debian_12.yml

This PR adds Debian 12 (aka bookworm) support to the role.
The workflow fails at the moment because there is no roles-ansible/check-ansible-debian-bookworm-action repo yet. As soon as @DO1JLR has created the repo it should pass all checks.
Furthermore i fixed some small oversights in older debian defaults.

feat: debian 12 support and small config fixes for debian

---

.ansible-lint

Enhancement: Ignore var-naming[no-role-prefix] ansible-lint rule that fails expectedly
Reason: ansible-lint recently added a rule `var-naming[no-role-prefix]` that fails expectedly, this role generally uses `sshd` instead of `ansible_sshd`, and also vars from other roles e.g. `firewall_`.
Result: ansible-lint ignores this rule and passes.

ci: Ignore var-naming[no-role-prefix] ansible-lint rule that fails expectedly

---

handlers/main.yml
tasks/find_ports.yml
tasks/install.yml
tasks/install_service.yml
tasks/variables.yml
tests/tasks/restore.yml
tests/tests_firewall_selinux.yml

Enhancement:
Support `inject_facts_as_vars = false` in ansible.cfg.
The setting is considered safer because a compromised host cannot inject facts into variables.
Reason:
Minor security enhancement.
This setting is also recommended in some tuning guides like
https://docs.openstack.org/kolla-ansible/wallaby/user/ansible-tuning.html#fact-variable-injection
and issue mitigation guides:
https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#when-is-it-unsafe-to-bulk-set-task-arguments-from-a-variable
`ansible_facts` are used only with one name. Previously for example `ansible_facts['os_family']` was also used as `ansible_os_family`. This helps maintainability.
Result:
Support `inject_facts_as_vars = false`. If setting is `true`, situation still works as expected.
Also drop …

fix: Support inject_facts_as_vars = false

---

.ansible-lint
.github/workflows/build_docs.yml
.github/workflows/markdownlint.yml
.github/workflows/pr-title-lint.yml
.github/workflows/test_converting_readme.yml
.github/workflows/woke.yml
.markdownlint.yaml
.pandoc_template.html5
CODE_OF_CONDUCT.md
README.md

Enhancement: Add markdownlint, test_converting_readme, and build_docs GitHub workflows
Reason:
* markdownlint runs against markdown files to ensure correct syntax and avoid any issues with converting README.md to HTML
* test_converting_readme converts README.md > HTML and uploads this test artifact to ensure that conversion works fine
* build_docs converts README.md > HTML and pushes the result to the docs branch to publish dosc to GitHub pages site
* Rename commitlint.yml workflow into pr-title-lint for clarity

ci: Add markdownlint, test_converting_readme, and build_docs workflows

---

tasks/install.yml
tasks/install_service.yml
templates/sshd.service.j2
templates/sshd@.service.j2
tests/tests_runtime_directory.yml

Enhancement: Avoid creation of runtime directory in home
Reason: The d6abe9c0325183180e6f83ba14c28781b9e6c6b9 changed the directories to be relative, but did not update tasks
Result: The playbook should create the runtime directory in the right place.
Issue Tracker Tickets (Jira or BZ if any): #264

fix: Avoid creation of runtime directories in home

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version v0.23.0

docs(changelog): version v0.23.0 [citest skip]

---

.ansible-lint
.github/workflows/ansible-lint.yml
.gitignore
.markdownlint.yaml
.ostree/get_ostree_data.sh
meta/make_ostree_packages_files
tests/tests_all_options.yml
tox.ini
vars/main.yml

The old ansible-community ansible-lint is deprecated.  There is a
new ansible-lint github action.
The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to convert the role to collection format before running
ansible-test.
This also requires tox-lsr 3.2.1
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
Fix ansible-lint and ansible-test issues reported by the
latest 2.16 versions.

ci: Use supported ansible-lint action; run ansible-lint against the collection

---

.github/workflows/ansible-debian-check.yml
.github/workflows/ansible-ubuntu.yml
handlers/main.yml
tasks/find_ports.yml
tasks/install.yml
tasks/install_service.yml
templates/sshd.service.j2
templates/sshd.socket.j2
templates/sshd@.service.j2
tests/tasks/restore.yml
tests/tasks/setup.yml
tests/tests_all_options.yml
tests/tests_alternative_file.yml
tests/tests_alternative_file_role.yml
tests/tests_include_present.yml
tests/tests_runtime_directory.yml
tests/tests_sysconfig.yml
tests/tests_systemd_services.yml
vars/Debian_10.yml
vars/Debian_11.yml
vars/Debian_12.yml
vars/Fedora.yml
vars/Fedora_37.yml
vars/RedHat_7.yml
vars/RedHat_8.yml
vars/RedHat_9.yml
vars/Ubuntu_20.yml
vars/Ubuntu_22.yml
vars/main.yml

Enhancement: Update systemd units to reflect OS defaults
Reason: The systemd units were based on some old ubuntu/debian and never updated to match current versions.
Result: The generated units include all important system defaults

fix: Review and update service units and socket unit to include distribution defaults

---

README.md

Enhancement: typo
Reason: such folder does not exist in RHEL system
Result: typo
Issue Tracker Tickets (Jira or BZ if any):

README.md typo in config word

---

tasks/install_service.yml
templates/sshd.service.j2
tests/tests_systemd_services.yml
vars/RedHat_7.yml
vars/main.yml

Enhancement: The service files on EL7 are generated with original content.
Reason: The centos7 containers report `ansible_facts["service_mgr"] =  "sysvinit"` which lead to skipping this test in the upstream CI. The CentOS7 is also the only OS that defines the environment file as a mandatory (missing the `-` sign in front of the filename), which caused the downstream tests executed against VMs to fail. But only in the main `sshd.service`. The minus sign is present in the instantiated `sshd@.service` to add even more confusion
Result: The role should generate original service files.
The diff in the generated `sshd.service` file before this change should be limited to the following change:
```diff
-EnvironmentFile=/etc/sysconfig/sshd …
```

fix: Fix service files generated on EL7 and workaround the tests for containers

---

README.md
meta/10_top.j2
tasks/install_config.yml
templates/sshd.service.j2
templates/sshd@.service.j2
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tests_second_service.yml
tests/tests_second_service_drop_in.yml
tests/tests_systemd_services.yml

The option was introduced in f6ae2094fe23eed94ce64eee1d0f5f1109dfe1da without documentation and intended use. The recent change f6ae2094fe23eed94ce64eee1d0f5f1109dfe1da propagated this option to the generated service files, which is resulting in unexpected results, when a user decided to set only `sshd_config_file` for the second sshd service such as:
* the service file points to the system-wide configuration file
* the system-wide configuration file will get include directive pointing to the directory of the second configuration file
This is an attempt to fix this by introducing some heuristics to guess if the user wants to set up second drop-in directory (ending with .d) or create a standalone configuration file.
Issue Tracker Tickets (Jira or BZ if any): …

fix: Document and streamline the sshd_main_config_file

---

tests/tests_second_service.yml
tests/tests_second_service_drop_in.yml

Some of our test suites require sshd2 to be completely stopped
and removed, or subsequent tests will fail.

test: ensure that sshd2 is completely stopped and removed

---

.github/workflows/ansible-lint.yml
.ostree/packages-runtime-CentOS-10.txt
.ostree/packages-runtime-CentOS-6.txt
.ostree/packages-runtime-CentOS-7.txt
.ostree/packages-runtime-CentOS-8.txt
.ostree/packages-runtime-CentOS-9.txt
.ostree/packages-runtime-RedHat-10.txt
.ostree/packages-testing-CentOS.txt
README.md
meta/main.yml
vars/RedHat_10.yml

According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
For each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. `el-10`?
This is not allowed by ansible-lint:
```
meta-no-tags: Tags must contain lowercase letters and digits only., invalid: 'el-10'
meta/main.yml:1
```
So we cannot use uppercase letters either.
Q: Why not use our own meta/main.yml field?
No other fields are allowed by ansible-lint:
``` …
```

fix: add support for EL10

---

README.md
meta/options_body
meta/options_match
templates/sshd_config.j2
templates/sshd_config_snippet.j2

Enhancement: Add new configuration options from OpenSSH 9.8
Reason: The CentOS 10 Stream and Fedora rawhide are getting updated to new OpenSSH version
Result: The new configuration options are usable through this role
Issue Tracker Tickets (Jira or BZ if any):

feat: Add new configuration options from OpenSSH 9.8

---

tasks/check_vars.yml
tasks/install.yml
tasks/install_config.yml
tasks/install_namespace.yml
tasks/install_service.yml
tests/tasks/backup.yml
tests/tasks/restore.yml
tests/tests_hostkeys_unsafe_path.yml
tests/tests_unsafe_options.yml

This is the replacement for the stale PR #245, where the reporter never came back to fix the CI issues, but we still consider that useful change.
Enhancement: Use quote command when calling shell/command modules.
Reason: The user suplied variables could split if they contain whitespace and cause unexpected behavior.
Result: User input is validated.

fix: use quote with command, shell and validate with variable

---

tests/tests_hostkeys_unsafe_path.yml

Setting TMPDIR globally causes problems on some platforms.
Instead, set it at the `block` level and put the role
invocation inside the block.

test: set TMPDIR in block of role invocation

---

.github/workflows/ansible-centos-check.yml
meta/options_body
meta/options_match
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tests_alternative_file.yml
tests/tests_alternative_file_role.yml

Issue Tracker Tickets (Jira or BZ if any): RHEL-68346 (workaround)

feat: New options in OpenSSH + fixes for bugx in OpenSSH 9.9p1

---

README.md
defaults/main.yml
handlers/main.yml
tasks/install.yml
tasks/install_config.yml
tasks/install_namespace.yml
tasks/install_service.yml
vars/AIX.yml

The change of sysconfig requires the full restart instead of only reload.
I did not figure out a better way to avoid doing both in this case, so comments and suggestions welcomed.
Fixes: #302

fix: Reload the service when needed

---

meta/10_top.j2
tasks/install.yml
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tasks/check_header.yml
tests/tests_all_options.yml
tests/tests_backup.yml
tests/tests_config_namespace.yml
tests/tests_firewall_selinux.yml
tests/tests_hostkeys_fips.yml
tests/tests_include_present.yml
vars/main.yml

Ansible 2.19 introduces some big changes
https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_core_2.19.html
A big change is that a boolean expression in a `when` or similar construct
must be converted to a boolean - we cannot rely on the implicit evaluation in
a boolean context.  For example, if `var` is some iterable, like a `dict`, `list`,
or `string`, you used to be able to evaluate an empty value in a boolean context:
```yaml
when: var  # do this only if var is not empty
```
You now have to explicitly test for empty using `length`:
```yaml
when: var | length > 0  # do this only if var is not empty
```
Similarly for `int` values - you cannot rely on `0` being evaluated as false
and non-zero true - you must explicitly compare the values with `==` or `!=`
In macros in …

refactor: Ansible 2.19 support

---

.github/workflows/ansible-debian-check.yml
meta/options_body
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tests_systemd_services.yml

Enhancement: Add a new configuration option `GSSAPIIndicators`.
Reason: The CentOS 10 comes with a new configuration option `GSSAPIIndicators`.
Result: The new configuration option can be used when configuring CentOS 10 machines.

fix: New configuration option in CentOS 10

---

README.md
defaults/main.yml
handlers/main.yml
tasks/find_bind_addresses.yml
tasks/find_ports.yml
tasks/install.yml
tasks/install_config.yml
tasks/install_service.yml
templates/sshd.socket.j2
tests/tests_systemd_socket_listen.yml
tests/tests_systemd_socket_port.yml
vars/Ubuntu_24.yml
vars/main.yml

Enhancement: Adjust generated systemd socket file to contain actual ports and addresses from the configuration file, add support for the systemctl daemon reload and sshd socket restart.
Reason: The new Ubuntu landed with changed socket file. We also need to reload systemd daemon when we change these, which was reported in #307. 
Result: The generated socket file matches configured port and addresses and systemd daemon is properly reloaded and sshd socket restarted on relevant changes.

feat: Support for daemon reload, socket restart and systemd socket file to match Ubuntu 24.04

---

.github/workflows/ansible-debian-check.yml
README.md
meta/main.yml
tests/tests_all_options.yml
vars/Debian_13.yml

Enhancement: Add support for Debian 13 (aka Trixie)
Reason: 
Like two years ago (#283) the next debian release is near.
Debian 13 Release is planned for 2025-08-09 (https://wiki.debian.org/DebianTrixie)
Result: Support for Debian 13

feat: add Debian 13 support
