README.md
templates/sshd_config.j2
vars/Archlinux.yml
vars/Debian.yml
vars/RedHat_7.yml
vars/Ubuntu.yml

Found this amazing role and noticed a couple typos. Also wanted to add support for Archlinux as you've made it very easy to do! Thanks!

Minor typo fixes and add Archlinux support

---

vars/Ubuntu_12.yml
vars/Ubuntu_14.yml

Add precise, move 14.04 to specific configuration

---

defaults/main.yml
handlers/main.yml
tasks/main.yml

Fixes boolean sense issue
Add tags for OS compatibility and boolean stating role has run.

Fix issues raised in #22

---

meta/options_body
templates/sshd_config.j2
vars/Debian.yml

DebianBanner support

---

.gitignore
defaults/main.yml
handlers/main.yml
tasks/main.yml

Ansible23 fixes

---

vars/Debian_9.yml

Debian stretch has been released, copy Debian_8.yml into Debian_9.yml.

Add Debian 9 (stretch) vars

---

tasks/main.yml

Use the newer `package` module

* change `ansible_pkg_mgr` for package

---

defaults/main.yml

* defaults typo

---

vars/Ubuntu_18.yml

I copied it from Ubuntu_16.yml

Add Ubuntu_18.yml

---

README.md
defaults/main.yml
tasks/main.yml
tasks/sshd.yml

This is something I do to all my custom roles. It allow for any easy on off switch and helps in testing playbooks and in creating more dynamic playbooks.

Adds on/off toggle

---

vars/Ubuntu_18.yml

Remove deprecated SSH protocol 1 options
(https://salsa.debian.org/ssh-team/openssh/commit/fb87db8aa47d3508be8e5bb1d21897fa1f2eca90)

Remove deprecated options

---

tasks/install.yml

Propagates setting sshd_backup to template installation task (issue #105)

Backup of sshd_config dependent on variable

---

meta/main.yml
tasks/install.yml
tasks/main.yml
tasks/variables.yml

Hello! This fixes #102, resolving all of the ansible-lint errors.

Resolve lint errors

---

handlers/main.yml
tasks/install.yml
tasks/variables.yml

As ansible 2.7 is not out yet, if you are interested in this PR, maybe it should be accepted [after 2.7 is out](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_7.html).

Updates syntax to Ansible 2.7 era

---

templates/sshd_config.j2

Remove duplicate GatewayPorts

---

README.md
examples/example-root-login.yml

Provide simple example playbook in the examples directory

examples: Provide simple example playbook

---

README.md
meta/main.yml

Add 9 to EL and replace the versions of Fedora with all in meta/main.yml. Update README.md based on the changes.

Update meta data and README

---

.travis.yml
README.md
defaults/main.yml
examples/example-accept-env.yml
tasks/install.yml
tests/tests_config_namespace.yml
tests/tests_sshd_enable.yml

The new name better explains what the option does.

Rename sshd_namespace_append to sshd_config_namespace

---

tests/tasks/setup.yml
tests/tests_alternative_file.yml
tests/tests_alternative_file_role.yml
tests/tests_backup.yml
tests/tests_hostkeys.yml
tests/tests_hostkeys_role.yml
tests/tests_match.yml
tests/tests_match_iterate.yml
tests/tests_precedence.yml
tests/tests_sysconfig.yml
vars/RedHat_9.yml

This adds a proper support for RHEL9 (based on latest Fedora) and adjusts test for that.

Add support for RHEL 9 and adjust tests for it

---

meta/01_ansible_head.j2
templates/sshd_config.j2
templates/sysconfig.j2

BZ#2006230, BZ#2006231, BZ#2006233

Use {{ ansible_managed | comment }} to fix multi-line ansible_managed

---

tasks/install.yml

Fix runtime directory check condition

---

.github/workflows/ansible-fedora.yml
.github/workflows/ansible-ubuntu.yml
vars/common.yml

Remove kvm from virtualization platoforms

---

meta/options_body
templates/sshd_config.j2
templates/sshd_config_snippet.j2

Add support for the new RSAMinSize parameter.

add parameter RSAMinSize

---

.github/workflows/changelog_to_tag.yml

Keep the `v` prefix in the version/tag

keep v prefix in version/tag

---

README.md
handlers/main.yml
vars/OpenWrt.yml

With this PR I'd like to provide support for OpenWrt. It has been tested on OpenWrt 22.03.
Please let me know if anything is missing.

Adding support for OpenWrt

---

meta/options_body
tasks/install.yml
tasks/install_config.yml
tasks/install_namespace.yml
templates/sshd.service.j2
templates/sshd.socket.j2
templates/sshd@.service.j2
templates/sshd_config.j2
templates/sshd_config_snippet.j2
tests/tests_all_options.yml
vars/main.yml

Introduce automatic test for new configuration options in OpenSSH and add missing options so far

---

vars/Alpine.yml

Adding basic vars for Alpine OS.

Initial configuration for Alpine OS

---

.github/workflows/ansible-alpine.yml
README.md
meta/main.yml
tests/tests_all_options.yml
tests/tests_config_namespace.yml
vars/Alpine.yml

Run CI also on Alpine

---

CHANGELOG.md

This is a draft for the next release.

release 0.18.1

---

CHANGELOG.md

docs(changelog): version v0.19.0

---

CHANGELOG.md

Create changelog update and release for version v0.20.0

docs(changelog): version v0.20.0 [citest skip]

---

.README.html
CHANGELOG.md
contributing.md

Update changelog and .README.html for version v0.21.0

docs(changelog): version v0.21.0 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version v0.22.0
Enhancement:
Reason:
Result:
Issue Tracker Tickets (Jira or BZ if any):

docs(changelog): version v0.22.0 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version v0.23.2

docs(changelog): version v0.23.2 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version v0.23.3

docs(changelog): version v0.23.3 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version v0.23.4

docs(changelog): version v0.23.4 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version v0.23.5

docs(changelog): version v0.23.5 [citest skip]

---

CHANGELOG.md

docs(changelog): version v0.25.0 [citest skip]

---

CHANGELOG.md

docs(changelog): version v0.26.0

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version v0.27.0

docs(changelog): version v0.27.0 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version v0.27.1

docs(changelog): version v0.27.1 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version v0.28.0
Signed-off-by: Matt Willsher <matt@monki.org.uk>

docs(changelog): version v0.28.0 [citest skip]
